version: "3.8"

services:
  ast-nginx:
    container_name: ast-nginx
    image: nginx:stable-alpine
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "7000:7000"
      - "7010:7010"
    depends_on:
      - ast-php-fpm
    restart: unless-stopped

  ast-php-fpm:
    container_name: ast-php-fpm
    build:
      context: .
      dockerfile: docker/php/8.2/fpm/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - ast-mysql

  ast-php-cli:
    container_name: ast-php-cli
    build:
      context: .
      dockerfile: docker/php/8.2/cli/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - ast-mysql

  ast-mysql:
    container_name: ast-mysql
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - ast-mysql-db-data:/bitnami/mysql/data
    restart: unless-stopped

networks:
  default:
    external: true
    name: ast-network

volumes:
  ast-mysql-db-data:
